# Generated by Django 4.2 on 2023-04-13 19:39

import django.core.validators
from django.db import migrations, models
import myMusicApp.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), myMusicApp.web.models.validate_only_alphanumeric]),
        ),
    ]
